Updated Transaction & Account Properties with mocked tests
VMelnalksnis/NordigenDotNet pull request #174
Opened 2023-11-13 17:21 UTC by itisNathaniel

Resolves #167 and #164

Implements HTTP mocked data tests for fields which are returned by banks but are not returned from the Nordigen/GoCardless sandbox.

---

Superceeds PRs #167 and #168

2023-11-13 17:32 UTC, itisNathaniel commented
Hi @VMelnalksnis, have implemented the tests here and moved the PR changes into one place, thanks!

2023-11-14 08:53 UTC, VMelnalksnis requested changes

2023-11-14 08:53 UTC, VMelnalksnis commented on README.md
> +# Testing
Since this README is also used for the NuGet package, it would be better to either move this to [CONTRIBUTING.md](https://github.com/VMelnalksnis/NordigenDotNet/blob/master/CONTRIBUTING.md), or below Known issues.

2023-11-14 08:53 UTC, VMelnalksnis commented on tests/VMelnalksnis.NordigenDotNet.Tests.Integration/Accounts/AccountClientTests.cs
> +		accountDetails.Should().BeEquivalentTo(
If using multiple assertions, should add an `AssertionScope`:
```suggestion
        using var scope = new AssertionScope();
        
		accountDetails.Should().BeEquivalentTo(
```

2023-11-14 08:53 UTC, VMelnalksnis commented on tests/VMelnalksnis.NordigenDotNet.Tests/Accounts/AccountClientTests.cs
> +		var filePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, $"../../../Stubs/{testPath}");
I haven't tried it this way, but in general I avoid using the filesystem for test data. It causes issues when using automated testing, for example, automatically running tests that cover changed code on build in Rider. I prefer using `EmbedderResource`, for example see https://github.com/VMelnalksnis/Gnomeshade/blob/master/tests/Gnomeshade.WebApi.Tests.Integration/V1/Controllers/Iso20022/TestData.cs

2023-11-14 08:53 UTC, VMelnalksnis commented on tests/VMelnalksnis.NordigenDotNet.Tests/Accounts/AccountClientTests.cs
> +		var details = await accountClient.GetDetails(
Since the id does not matter here:
```suggestion
		var details = await accountClient.GetDetails(Guid.NewGuid());
```

2023-11-14 08:53 UTC, VMelnalksnis commented on tests/VMelnalksnis.NordigenDotNet.Tests/Accounts/AccountClientTests.cs
> +		var bookingDate = new DateTime(2023, 11, 8, 10, 05, 00);
Should stick to `NodaTime` types:
```suggestion
		var bookingDate = new LocalDateTime(2023, 11, 8, 10, 05);
```

2023-11-14 08:53 UTC, VMelnalksnis commented on tests/VMelnalksnis.NordigenDotNet.Tests/MockHttp/MockHttpHandler.cs
> +	private string _json;
```suggestion
	private readonly string _json;
```

2023-11-14 20:49 UTC, itisNathaniel commented on tests/VMelnalksnis.NordigenDotNet.Tests/MockHttp/MockHttpHandler.cs
> +	private string _json;
Updated this

2023-11-14 20:49 UTC, itisNathaniel commented on tests/VMelnalksnis.NordigenDotNet.Tests/Accounts/AccountClientTests.cs
> +		var bookingDate = new DateTime(2023, 11, 8, 10, 05, 00);
Updated to use NodaTime types

2023-11-14 20:49 UTC, itisNathaniel commented on tests/VMelnalksnis.NordigenDotNet.Tests/Accounts/AccountClientTests.cs
> +		var details = await accountClient.GetDetails(
Updated

2023-11-14 20:49 UTC, itisNathaniel commented on tests/VMelnalksnis.NordigenDotNet.Tests/Accounts/AccountClientTests.cs
> +		var filePath = Path.Combine(AppDomain.CurrentDomain.BaseDirectory, $"../../../Stubs/{testPath}");
Updated this, thanks

2023-11-14 20:49 UTC, itisNathaniel commented on tests/VMelnalksnis.NordigenDotNet.Tests.Integration/Accounts/AccountClientTests.cs
> +		accountDetails.Should().BeEquivalentTo(
Updated this

2023-11-14 20:49 UTC, itisNathaniel commented on README.md
> +# Testing
Updated

2023-11-14 20:50 UTC, itisNathaniel commented
Thanks @VMelnalksnis, have resolved the above

2023-11-16 18:17 UTC, VMelnalksnis commented on tests/.DS_Store
Looks like a macOS config file. Can you remove this, and also add this to .gitignore?

2023-11-16 18:39 UTC, itisNathaniel commented on tests/.DS_Store
Missed this one, thanks, it's the macOS `thumbs.db` equivilant, have added and enforced it in the gitignore

2023-11-18 15:14 UTC, itisNathaniel commented
Have rebased in main so should be good to merge if all looks good with the changes above

2023-11-26 09:36 UTC, VMelnalksnis approved these changes

2023-11-26 09:39 UTC, merged