Update DateTime datatype to support non-Zulu time values
VMelnalksnis/NordigenDotNet pull request #203
Opened 2024-01-21 12:27 UTC by itisNathaniel

Resolves #202 by using the `OffsetDateTime` type instead of `Instant` 

Adds new unit tests to cover these additonal scenarios

2024-01-23 06:18 UTC, VMelnalksnis commented
Am I missing something about GitHub actions, or does every repository really need to re-implement some sort of secret access control for PRs from public forks?

If I use `pull_request`, then there are the built in security settings which will ask for approval for each run or for first run from other users, but `pull_request` target does not give secrets to public forks. If I just use the `pull_request_target`, then those checks are gone and I have to add them manually, either using labels or something like this https://michaelheap.com/access-secrets-from-forks/. But I don't want yet another thing to maintain, especially related to security.

2024-01-28 19:57 UTC, itisNathaniel commented
It does seem that there isn't a great solution used everywhere for this to handle secrets in untrusted forks.

`pull_request_target` and switching the branch creates security issues of it's own, but perhaps that plus adding a [manual approval step](https://github.com/marketplace/actions/manual-workflow-approval) as a first step before running any job requiring secrets would be the best way to handle it to force a re-review on each code change to ensure no malicious code has been added.

2024-02-03 07:59 UTC, VMelnalksnis commented on tests/VMelnalksnis.NordigenDotNet.Tests/Accounts/AccountClientTests.cs
> +				ExchangeRate = decimal.Parse("0.00"),
`decimal.Parse` is culture specific, and will break depending on system settings. Should use decimal literals (`0.00m`) in tests instead.

2024-02-03 08:00 UTC, VMelnalksnis requested changes

2024-02-03 08:00 UTC, VMelnalksnis commented on tests/VMelnalksnis.NordigenDotNet.Tests/Accounts/AccountClientTests.cs
> +				ExchangeRate = decimal.Parse("0.00"),
`decimal.Parse` is culture specific, and will break depending on system settings. Should use decimal literals (`0.00m`) in tests instead.

2024-02-03 12:23 UTC, itisNathaniel commented on tests/VMelnalksnis.NordigenDotNet.Tests/Accounts/AccountClientTests.cs
> +				ExchangeRate = decimal.Parse("0.00"),
These are now updated, thanks @VMelnalksnis

2024-02-03 12:51 UTC, VMelnalksnis approved these changes

2024-02-03 12:51 UTC, merged